### ISSUE TITLE
ESPHOME 1.19 break component

### ISSUE THREAD

**Issue by jperquin** [ayufan/esphome-components#19]
During compilation following warnings appear, which do not appear to be major, but the resulting firmware does no longer function on the ESP32 board.

Compiling /data/ttgo_trv_vzvn_beneden/.pioenvs/ttgo_trv_vzvn_beneden/src/esphome/components/eq3_v2/eq3_cmd.cpp.o
src/esphome/components/eq3_v2/eq3.cpp: In member function 'void EQ3Climate::parse_state(const string&)':
src/esphome/components/eq3_v2/eq3.cpp:215:3: warning: 'esphome::climate::Climate::away' is deprecated: away is deprecated, use preset instead [-Wdeprecated-declarations]
   away = state->mode.away_mode;
   ^
In file included from src/esphome/components/eq3_v2/eq3.h:5:0,
                 from src/esphome/components/eq3_v2/eq3.cpp:1:
src/esphome/components/climate/climate.h:196:18: note: declared here
   bool away{false};
                  ^
src/esphome/components/eq3_v2/eq3.cpp:215:3: warning: 'esphome::climate::Climate::away' is deprecated: away is deprecated, use preset instead [-Wdeprecated-declarations]
   away = state->mode.away_mode;
   ^
In file included from src/esphome/components/eq3_v2/eq3.h:5:0,
                 from src/esphome/components/eq3_v2/eq3.cpp:1:
src/esphome/components/climate/climate.h:196:18: note: declared here
   bool away{false};
                  ^
src/esphome/components/eq3_v2/eq3.cpp: In member function 'virtual esphome::climate::ClimateTraits EQ3Climate::traits()':
src/esphome/components/eq3_v2/eq3.cpp:275:37: warning: 'void esphome::climate::ClimateTraits::set_supports_auto_mode(bool)' is deprecated: This method is deprecated, use set_supported_modes() instead [-Wdeprecated-declarations]
   traits.set_supports_auto_mode(true);
                                     ^
In file included from src/esphome/components/climate/climate.h:8:0,
                 from src/esphome/components/eq3_v2/eq3.h:5,
                 from src/esphome/components/eq3_v2/eq3.cpp:1:
src/esphome/components/climate/climate_traits.h:54:8: note: declared here
   void set_supports_auto_mode(bool supports_auto_mode) { set_mode_support_(CLIMATE_MODE_AUTO, supports_auto_mode); }
        ^
src/esphome/components/eq3_v2/eq3.cpp:279:37: warning: 'void esphome::climate::ClimateTraits::set_supports_heat_mode(bool)' is deprecated: This method is deprecated, use set_supported_modes() instead [-Wdeprecated-declarations]
   traits.set_supports_heat_mode(true);
                                     ^
In file included from src/esphome/components/climate/climate.h:8:0,
                 from src/esphome/components/eq3_v2/eq3.h:5,
                 from src/esphome/components/eq3_v2/eq3.cpp:1:
src/esphome/components/climate/climate_traits.h:58:8: note: declared here
   void set_supports_heat_mode(bool supports_heat_mode) { set_mode_support_(CLIMATE_MODE_HEAT, supports_heat_mode); }
        ^
src/esphome/components/eq3_v2/eq3.cpp:280:33: warning: 'void esphome::climate::ClimateTraits::set_supports_away(bool)' is deprecated: This method is deprecated, use set_supported_presets() instead [-Wdeprecated-declarations]
   traits.set_supports_away(false); // currently not working
                                 ^
In file included from src/esphome/components/climate/climate.h:8:0,
                 from src/esphome/components/eq3_v2/eq3.h:5,
                 from src/esphome/components/eq3_v2/eq3.cpp:1:
src/esphome/components/climate/climate_traits.h:119:8: note: declared here
   void set_supports_away(bool supports) {

**Comment by dedors** [comment]
Probably the same here, upgraded to 1.20.3 and it stopped working.  Also tried 2021.8.2.

**Comment by ayufan** [comment]
Do you have some info what does not work?

**Comment by jperquin** [comment]
BT connections to TRV's keep failing / retrying..

**Comment by dedors** [comment]
I could ping, but not connect via Wifi (to read the logs or flash). After a while it went completely offline. And Home Assistant never received any data.

Rather lucky coincidence, I had a warning regarding power_save_mode on an other device when trying to connect to view logs
`power_save_mode NONE is incompatible with esp32_ble_tracker. Please remove the power save mode. See also https://github.com/esphome/issues/issues/2141#issuecomment-865688582.`

I didn't get a warning when connecting to this device (probably because no esp32_ble_tracker is used), but removing it just fixed the issue!

**Comment by jperquin** [comment]
Hi Dedors; so what you are saying is that ESPHOME 1.19+ works as long as you do not use power_save_mode NONE?

I have a bunch of devices running on 1.18 WITH power_save_mode NONE and that works fine..

**Comment by ayufan** [comment]
The device interoperability is tricky with BT/WiFi. This integration kind of forbids usage of `esp32_ble_tracker` concurrently. At least in PL there's no heating season yet, so I plan to take a look soon at this :)

**Comment by dedors** [comment]
> 
> 
> Hi Dedors; so what you are saying is that ESPHOME 1.19+ works as long as you do not use power_save_mode NONE?
> 
> I have a bunch of devices running on 1.18 WITH power_save_mode NONE and that works fine..

That's what I think. Last version I used was 1.17 or 1.18 and I had no problem there. Had 10+ attempts failed with 1.20, and removing the power_save_mode just fixed it.


> 
> 
> The device interoperability is tricky with BT/WiFi. This integration kind of forbids usage of `esp32_ble_tracker` concurrently. At least in PL there's no heating season yet, so I plan to take a look soon at this :)

In the comment from the warning above:
`power_save_mode: NONE should no longer be required with the newer framework, as (hopefully) the issues that previously made the option necessary are fixed now.`
Maybe there is also no downside in removing it now.

**Comment by jperquin** [comment]
I can confirm that omitting power_save mode fixes the issue.

Following config still throws a bunch of errors during compiling in ESPHOME v2021.8.2, but none are critical.

```
esphome:
  name: ttgo_test
  platform: ESP32
  board: mhetesp32devkit
#  board: nodemcu-32s
  platformio_options:
    #set board frequency to 240 MHz
    board_build.f_cpu: 240000000L
    #set flash frequency to 80 MHz
    board_build.f_flash: 80000000L
#  arduino_version: recommended
#  arduino_version: latest
#  arduino_version: dev
  board_flash_mode: dout

#Wifi connection
wifi:
#  power_save_mode: none
  networks:
  - ssid: !secret not_wifi_ssid
    password: !secret not_wifi_pw


debug:

# Enable logging
logger:
  level: debug

#Enable MQTT
mqtt:
  broker: 192.168.50.94
  username: !secret dd_mqtt_secure_user
  password: !secret dd_mqtt_secure_pw
  client_id: "ttgo_test"
  keepalive: 60s
#  reboot_timeout: 10min
  discovery_prefix: homeassistant
  topic_prefix: ttgo_test
  birth_message:
    topic: ttgo_test/available
    payload: online
  will_message:
    topic: ttgo_test/available
    payload: offline

# time is required by `eq3_v2` to send
# an accurate time spec when requesting
# current state
time:
  - platform: sntp
    id: sntp_time
    timezone: CET-1CEST,M3.5.0,M10.5.0/3

# refresh component state every 10mins,
# and announce it to Home Assistant API
climate:
  - platform: eq3_v2
    id: ttgo_test_trv
    name: "TTGO TEST TRV"
    mac_address: 00:1A:22:12:5D:C8
    update_interval: 10min
    valve: # optional, allows to see valve state in %
      name: "TTGO Test TRV State"
      expire_after: 61min # only needed when using MQTT
    temperature_sensor: helper_ttgo_test_trv

sensor:
  - platform: wifi_signal
    name: " WiFi Signal"

# HA temp sensors for eq3 (API)
  - platform: mqtt_subscribe
    name: HA Helper TRV
    internal: true
    topic: room1_temp/state
    id: helper_ttgo_test_trv

#Device Status
binary_sensor:
  - platform: status
    name: "Device Status"

#General info
text_sensor:
  - platform: wifi_info
    ip_address:
      name: "ttgo_test_ip"
    ssid:
      name: "ttgo_test_ssid"
  - platform: version
    name: "ttgo_test ESPHome Version"

switch:
  - platform: restart
    name: "ttgo_test Module Restart"
    id: restart_switch

# allow to force refresh component state
  - platform: template
    name: "Refresh TTGO Test TRV"
    lambda: "return false;"
    turn_on_action:
      - component.update: ttgo_test_trv
```

Just as an (unrelated) FYI: Having very good results with the LilyGO TTGO T-Micro32 Development Board - ESP32 PICO D4 (see [here](https://www.tinytronics.nl/shop/en/development-boards/microcontroller-boards/with-wi-fi/lilygo-ttgo-t-micro32-development-board-esp32-pico-d4)) and external antenna ([here](https://www.tinytronics.nl/shop/en/communication-and-signals/wireless/antennas/2.4ghz/2.4ghz-antenna-sma-ufl)) with a small box printed in PLA as it mitigates the range limitations of the more common ESP32 WROOM boards without antenna.

![IMG_0656](https://user-images.githubusercontent.com/46850501/131973698-04e7b799-94c9-4a18-b5da-ab1c194b55cd.jpeg)

![image](https://user-images.githubusercontent.com/46850501/131973317-e38c4021-2e44-4279-b2ba-1d27b95be51a.png)
and
![image](https://user-images.githubusercontent.com/46850501/131973387-871b802a-5aed-4c9b-85a1-2ba3cdbee050.png)
